-- MySQL Script generated by MySQL Workbench
-- Mon Jun  4 22:42:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisso` DEFAULT CHARACTER SET utf8 ;
USE `sisso` ;

-- -----------------------------------------------------
-- Table `sisso`.`tipomodalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`tipomodalidad` (
  `idtipoModalidad` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipoModalidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `tipomodalidad` (`idtipoModalidad`, `descripcion`, `nombre`) VALUES
(1, 'Modalidad de trabajo de grado', 'Trabajo de grado'),
(2, 'Modalidad de informatica Social', 'Informatica Social');


-- -----------------------------------------------------
-- Table `sisso`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`proyecto` (
  `idproyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreProyecto` VARCHAR(45) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFinalizacion` DATE NULL DEFAULT NULL,
  `presuesto` INT(11) NULL DEFAULT NULL,
  `problacionBeneficiada` INT(11) NULL DEFAULT NULL,
  `nombreResponsable` VARCHAR(55) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `objetivoGeneral` VARCHAR(255) NOT NULL,
  `tipoModalidad_idtipoModalidad` INT(11) NOT NULL,
  `EstadoProyecto` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idproyecto`),
  INDEX `fk_proyecto_tipoModalidad1_idx` (`tipoModalidad_idtipoModalidad` ASC),
  CONSTRAINT `fk_proyecto_tipoModalidad1`
    FOREIGN KEY (`tipoModalidad_idtipoModalidad`)
    REFERENCES `sisso`.`tipomodalidad` (`idtipoModalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1006
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisso`.`anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`anexo` (
  `idAnexo` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreAnexo` VARCHAR(45) NOT NULL,
  `Ruta` VARCHAR(200) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `proyecto_idprotecto` INT(11) NOT NULL,
  `created` DATETIME(6) NOT NULL,
  `user` INT(11) NOT NULL,
  PRIMARY KEY (`idAnexo`),
  INDEX `fk_Anexo_proyecto1_idx` (`proyecto_idprotecto` ASC),
  CONSTRAINT `fk_Anexo_proyecto1`
    FOREIGN KEY (`proyecto_idprotecto`)
    REFERENCES `sisso`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisso`.`atributocalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`atributocalidad` (
  `idatributoCalidad` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idatributoCalidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisso`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`evaluacion` (
  `idevaluacion` INT(11) NOT NULL AUTO_INCREMENT,
  `resultado` DECIMAL(10,3) NULL DEFAULT NULL,
  `proyecto_idproyecto` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `actualizacion` DATE NOT NULL,
  PRIMARY KEY (`idevaluacion`),
  INDEX `fk_evaluacion2_proyecto1_idx` (`proyecto_idproyecto` ASC),
  CONSTRAINT `fk_evaluacion2_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto`)
    REFERENCES `sisso`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisso`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`tipo` (
  `idTipo` INT(11) NOT NULL,
  `descripcionTipo` VARCHAR(45) NULL DEFAULT NULL,
  `nombreTipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `tipo` (`idTipo`, `descripcionTipo`, `nombreTipo`) VALUES
(1, 'Administrador', 'Administrador'),
(2, 'Docente', 'Docente'),
(3, 'Estudiante', 'Estudiante'),
(4, 'Egresado', 'Egresado');


-- -----------------------------------------------------
-- Table `sisso`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`usuario` (
  `codigo` INT(11) NOT NULL,
  `nombres` VARCHAR(55) NULL DEFAULT NULL,
  `apellidos` VARCHAR(55) NULL DEFAULT NULL,
  `celular` VARCHAR(11) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_idTipo` INT(11) NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_usuario_tipo1_idx` (`tipo_idTipo` ASC),
  CONSTRAINT `fk_usuario_tipo1`
    FOREIGN KEY (`tipo_idTipo`)
    REFERENCES `sisso`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `usuario` (`codigo`, `nombres`, `apellidos`, `celular`, `correo`, `tipo_idTipo`, `estado`, `password`) VALUES
(62535, 'Administrador', 'Administrador', '3100000000', 'ucatolicasisso@gmail.com', 1, 'A', '$2y$10$2ZMH.nmt.XvdbYONoVeUC.UBJHYprNWMDpLUIeJuyGflHkqCsM//a');


-- -----------------------------------------------------
-- Table `sisso`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`calificacion` (
  `idcalificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` INT(11) NOT NULL,
  `atributoCalidad_idatributoCalidad` INT(11) NOT NULL,
  `usuario_codigo` INT(11) NOT NULL,
  `evaluacion_idevaluacion` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `actualizacion` DATE NOT NULL,
  PRIMARY KEY (`idcalificacion`),
  INDEX `fk_calificacion_atributoCalidad1_idx` (`atributoCalidad_idatributoCalidad` ASC),
  INDEX `fk_calificacion_usuario1_idx` (`usuario_codigo` ASC),
  INDEX `fk_calificacion_evaluacion1_idx` (`evaluacion_idevaluacion` ASC),
  CONSTRAINT `fk_calificacion_atributoCalidad1`
    FOREIGN KEY (`atributoCalidad_idatributoCalidad`)
    REFERENCES `sisso`.`atributocalidad` (`idatributoCalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_evaluacion1`
    FOREIGN KEY (`evaluacion_idevaluacion`)
    REFERENCES `sisso`.`evaluacion` (`idevaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_usuario1`
    FOREIGN KEY (`usuario_codigo`)
    REFERENCES `sisso`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisso`.`matriz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`matriz` (
  `iditemrmatriz` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `posX` INT(11) NOT NULL,
  `posY` INT(11) NOT NULL,
  `valor` DECIMAL(10,5) NOT NULL,
  `usuario_codigo` INT(11) NOT NULL,
  `evaluacion_idevaluacion` INT(11) NOT NULL,
  `actualizacion` DATE NOT NULL,
  PRIMARY KEY (`iditemrmatriz`),
  INDEX `fk_evaluacion_atributoCalidad1_idx` (`posX` ASC),
  INDEX `fk_evaluacion_atributoCalidad2_idx` (`posY` ASC),
  INDEX `fk_matriz_usuario1_idx` (`usuario_codigo` ASC),
  INDEX `fk_matriz_evaluacion1_idx` (`evaluacion_idevaluacion` ASC),
  CONSTRAINT `fk_evaluacion_atributoCalidad1`
    FOREIGN KEY (`posX`)
    REFERENCES `sisso`.`atributocalidad` (`idatributoCalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_atributoCalidad2`
    FOREIGN KEY (`posY`)
    REFERENCES `sisso`.`atributocalidad` (`idatributoCalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriz_evaluacion1`
    FOREIGN KEY (`evaluacion_idevaluacion`)
    REFERENCES `sisso`.`evaluacion` (`idevaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriz_usuario1`
    FOREIGN KEY (`usuario_codigo`)
    REFERENCES `sisso`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 148
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisso`.`token_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`token_usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NOT NULL,
  `token` VARCHAR(200) NOT NULL,
  `status` INT(11) NOT NULL,
  `created` DATETIME(6) NOT NULL,
  `used` DATETIME NULL DEFAULT NULL,
  `user` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user`)
    REFERENCES `sisso`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisso`.`usuario_has_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`usuario_has_proyecto` (
  `usuario_codigo` INT(11) NOT NULL,
  `protecto_idprotecto` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_codigo`, `protecto_idprotecto`),
  INDEX `fk_usuario_has_protecto_protecto1_idx` (`protecto_idprotecto` ASC),
  INDEX `fk_usuario_has_protecto_usuario_idx` (`usuario_codigo` ASC),
  CONSTRAINT `fk_usuario_has_protecto_protecto1`
    FOREIGN KEY (`protecto_idprotecto`)
    REFERENCES `sisso`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_protecto_usuario`
    FOREIGN KEY (`usuario_codigo`)
    REFERENCES `sisso`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisso`.`usuario_temporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisso`.`usuario_temporal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(160) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `codigo` INT(11) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `tipo` INT(11) NOT NULL,
  `created` DATETIME(6) NOT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

USE `sisso` ;

-- -----------------------------------------------------
-- function generate_report1_high
-- -----------------------------------------------------

DELIMITER $$
USE `sisso`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `generate_report1_high`(finicial date, ffinal date) RETURNS int(11)
BEGIN
DECLARE v_finished INTEGER DEFAULT 0;
DECLARE bajo NUMERIC(16);
DECLARE val NUMERIC(16,3);
DECLARE cursor_projects CURSOR FOR 
select 
(select resultado from evaluacion evalc where evalc.proyecto_idproyecto = proy.proyecto_idproyecto order by actualizacion desc LIMIT 1) as cval
from evaluacion proy, proyecto p where proy.proyecto_idproyecto = p.idproyecto 
and p.fechaRegistro between finicial and ffinal  group by proy.proyecto_idproyecto;
-- declare NOT FOUND handler
 DECLARE CONTINUE HANDLER 
        FOR NOT FOUND SET v_finished = 1;
SET bajo = 0;

OPEN cursor_projects;
get_val: LOOP
 FETCH cursor_projects INTO val;
 IF v_finished = 1 THEN 
	LEAVE get_val;
 END IF;
 IF val > 61 and val <= 100 THEN 
	SET bajo = bajo + 1;
 END IF;
END LOOP get_val;
CLOSE cursor_projects;
RETURN bajo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function generate_report1_low
-- -----------------------------------------------------

DELIMITER $$
USE `sisso`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `generate_report1_low`(finicial date, ffinal date) RETURNS int(11)
BEGIN
DECLARE v_finished INTEGER DEFAULT 0;
DECLARE bajo NUMERIC(16);
DECLARE val NUMERIC(16,3);
DECLARE cursor_projects CURSOR FOR 
select 
(select resultado from evaluacion evalc where evalc.proyecto_idproyecto = proy.proyecto_idproyecto order by actualizacion desc LIMIT 1) as cval
from evaluacion proy, proyecto p where proy.proyecto_idproyecto = p.idproyecto 
and p.fechaRegistro between finicial and ffinal  group by proy.proyecto_idproyecto;
-- declare NOT FOUND handler
 DECLARE CONTINUE HANDLER 
        FOR NOT FOUND SET v_finished = 1;
SET bajo = 0;

OPEN cursor_projects;
get_val: LOOP
 FETCH cursor_projects INTO val;
 IF v_finished = 1 THEN 
	LEAVE get_val;
 END IF;
 IF val > 0 and val <= 40 THEN 
	SET bajo = bajo + 1;
 END IF;
END LOOP get_val;
CLOSE cursor_projects;
RETURN bajo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function generate_report1_mid
-- -----------------------------------------------------

DELIMITER $$
USE `sisso`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `generate_report1_mid`(finicial date, ffinal date) RETURNS int(11)
BEGIN
DECLARE v_finished INTEGER DEFAULT 0;
DECLARE bajo NUMERIC(16);
DECLARE val NUMERIC(16,3);
DECLARE cursor_projects CURSOR FOR 
select 
(select resultado from evaluacion evalc where evalc.proyecto_idproyecto = proy.proyecto_idproyecto order by actualizacion desc LIMIT 1) as cval
from evaluacion proy, proyecto p where proy.proyecto_idproyecto = p.idproyecto 
and p.fechaRegistro between finicial and ffinal  group by proy.proyecto_idproyecto;
-- declare NOT FOUND handler
 DECLARE CONTINUE HANDLER 
        FOR NOT FOUND SET v_finished = 1;
SET bajo = 0;

OPEN cursor_projects;
get_val: LOOP
 FETCH cursor_projects INTO val;
 IF v_finished = 1 THEN 
	LEAVE get_val;
 END IF;
 IF val > 41 and val <= 60 THEN 
	SET bajo = bajo + 1;
 END IF;
END LOOP get_val;
CLOSE cursor_projects;
RETURN bajo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function sum_item
-- -----------------------------------------------------

DELIMITER $$
USE `sisso`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `sum_item`(idproject numeric, code_user numeric, atribute numeric) RETURNS decimal(10,5)
BEGIN
DECLARE income NUMERIC(16,5);
   SET income = 0;
   SELECT IFNULL(sum(valor),0) into income FROM matriz where evaluacion_idevaluacion=idproject and usuario_codigo=code_user and posY=atribute;
RETURN income;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
